-- MySQL Script generated by MySQL Workbench
-- Thu Oct 29 16:04:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testSystemDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testSystemDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testSystemDb` DEFAULT CHARACTER SET utf8 ;
USE `testSystemDb` ;

-- -----------------------------------------------------
-- Table `testSystemDb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userid_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Role` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`),
  UNIQUE INDEX `roleId_UNIQUE` (`roleId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Topic` (
  `topicId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topicId`),
  UNIQUE INDEX `topicId_UNIQUE` (`topicId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Test` (
  `testId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `topicId` INT NOT NULL,
  PRIMARY KEY (`testId`),
  UNIQUE INDEX `testId_UNIQUE` (`testId` ASC) VISIBLE,
  INDEX `fk_Test_Topic1_idx` (`topicId` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Topic1`
    FOREIGN KEY (`topicId`)
    REFERENCES `testSystemDb`.`Topic` (`topicId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Question` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NOT NULL,
  `testId` INT NOT NULL,
  PRIMARY KEY (`questionId`),
  UNIQUE INDEX `iquestionId_UNIQUE` (`questionId` ASC) VISIBLE,
  INDEX `fk_Question_Test1_idx` (`testId` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Test1`
    FOREIGN KEY (`testId`)
    REFERENCES `testSystemDb`.`Test` (`testId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Literature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Literature` (
  `literatureId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `questionId` INT NOT NULL,
  PRIMARY KEY (`literatureId`),
  UNIQUE INDEX `literatureId_UNIQUE` (`literatureId` ASC) VISIBLE,
  INDEX `fk_Literature_Question1_idx` (`questionId` ASC) VISIBLE,
  CONSTRAINT `fk_Literature_Question1`
    FOREIGN KEY (`questionId`)
    REFERENCES `testSystemDb`.`Question` (`questionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Link` (
  `linkId` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(250) NOT NULL,
  `literatureId` INT NOT NULL,
  PRIMARY KEY (`linkId`),
  UNIQUE INDEX `LinkId_UNIQUE` (`linkId` ASC) VISIBLE,
  INDEX `fk_Link_Literature1_idx` (`literatureId` ASC) VISIBLE,
  CONSTRAINT `fk_Link_Literature1`
    FOREIGN KEY (`literatureId`)
    REFERENCES `testSystemDb`.`Literature` (`literatureId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Answer` (
  `answerId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `correct` TINYINT NOT NULL,
  `questionId` INT NOT NULL,
  PRIMARY KEY (`answerId`),
  INDEX `fk_Answer_Question1_idx` (`questionId` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`questionId`)
    REFERENCES `testSystemDb`.`Question` (`questionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`Statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`Statistic` (
  `statisticId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `correct` TINYINT NOT NULL,
  `userId` INT NOT NULL,
  `questionId` INT NOT NULL,
  INDEX `fk_User_has_Question_Question1_idx` (`questionId` ASC) VISIBLE,
  INDEX `fk_User_has_Question_User_idx` (`userId` ASC) VISIBLE,
  PRIMARY KEY (`statisticId`),
  UNIQUE INDEX `statisticId_UNIQUE` (`statisticId` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Question_User`
    FOREIGN KEY (`userId`)
    REFERENCES `testSystemDb`.`User` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Question_Question1`
    FOREIGN KEY (`questionId`)
    REFERENCES `testSystemDb`.`Question` (`questionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testSystemDb`.`UsersRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testSystemDb`.`UsersRole` (
  `userId` INT NOT NULL,
  `roleId` INT NOT NULL,
  INDEX `fk_User_has_Role_Role1_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_User_has_Role_User1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Role_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `testSystemDb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Role_Role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `testSystemDb`.`Role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
